name: Bundle Install

on:
  push:
    branches: [ main ]

jobs:
  bundle_install:
    name: Bundle Install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.0
    - name: Bundle Install
      run: |
        gem install bundler
        bundle install
